#!/usr/bin/env python3
"""Copy/generate everything in shared/ into both app targets.

    python3 tools/sync.py          # write generated files
    python3 tools/sync.py --check  # exit 1 if any generated file is stale (use in CI)

shared/ is the only place you edit content, rules, tokens or art. Files this
script writes carry a GENERATED header; never hand-edit them.

Outputs
  app-rn/src/generated/tokens.ts        design tokens as a typed const
  app-rn/src/generated/content.ts       words, rules, curriculum
  app-rn/src/generated/art.ts           SVG markup keyed by asset name
  ios/TamilTrain/Generated/Tokens.swift Color/size tokens for SwiftUI
  ios/TamilTrain/Assets.xcassets/...    one vector imageset per SVG
  ios/TamilTrainCore/Sources/TamilTrainCore/Resources/*.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared"
HEADER = "GENERATED by tools/sync.py from shared/. Do not edit."

writes: dict[Path, str | bytes] = {}


def put(path: str, text: str) -> None:
    writes[ROOT / path] = text


def load(rel: str) -> dict:
    return json.loads((SHARED / rel).read_text())


tokens = load("design/tokens.json")
words = load("content/words.json")
rules = load("content/rules.json")
curriculum = load("content/curriculum.json")


def camel_to_swift(name: str) -> str:
    return name  # already lowerCamel in tokens.json


# ------------------------------------------------------------ art inventory
def art_files() -> dict[str, Path]:
    """asset name -> svg path. Names: char-koo, word-paal, scene-station."""
    out = {}
    for folder, prefix in (("characters", "char"), ("words", "word"), ("scenes", "scene")):
        for f in sorted((SHARED / "assets" / folder).glob("*.svg")):
            out[f"{prefix}-{f.stem}"] = f
    return out


ART = art_files()

# ------------------------------------------------------------ React Native
put("app-rn/src/generated/tokens.ts",
    f"// {HEADER}\nexport const tokens = {json.dumps({k: v for k, v in tokens.items() if not k.startswith('_')}, indent=2, ensure_ascii=False)} as const;\n"
    "export type ColorName = keyof typeof tokens.color;\n")

put("app-rn/src/generated/content.ts",
    f"// {HEADER}\nimport type {{ ContentBundle }} from '../core/types';\n\n"
    f"export const content: ContentBundle = {json.dumps({'words': words, 'rules': rules, 'curriculum': curriculum}, indent=2, ensure_ascii=False)};\n")

art_lines = [f"// {HEADER}", "export const art = {"]
for name, f in ART.items():
    svg = f.read_text().strip().replace("\\", "\\\\").replace("`", "\\`")
    art_lines.append(f"  '{name}': `{svg}`,")
art_lines.append("} as const;\nexport type ArtName = keyof typeof art;\n")
put("app-rn/src/generated/art.ts", "\n".join(art_lines))

# ------------------------------------------------------------ iOS
def hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(round(int(h[i:i + 2], 16) / 255, 4) for i in (0, 2, 4))  # type: ignore


swift = [f"// {HEADER}", "import SwiftUI", "", "public enum Tokens {", "    public enum Palette {"]
for k, v in tokens["color"].items():
    r, g, b = hex_to_rgb(v)
    swift.append(f"        public static let {k} = Color(red: {r}, green: {g}, blue: {b}) // {v}")
swift.append("    }")
for group in ("size", "radius", "space"):
    swift.append(f"    public enum {group.capitalize()} {{")
    for k, v in tokens[group].items():
        swift.append(f"        public static let {k}: CGFloat = {v}")
    swift.append("    }")
swift.append(f"    public static let minTouchTarget: CGFloat = {tokens['touch']['minTarget']}")
swift.append(f"    public static let fontFamily = \"{tokens['font']['family']}\"")
swift.append("}\n")
put("ios/TamilTrain/Generated/Tokens.swift", "\n".join(swift))

put("ios/TamilTrain/Assets.xcassets/Contents.json",
    json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
for name, f in ART.items():
    base = f"ios/TamilTrain/Assets.xcassets/{name}.imageset"
    put(f"{base}/{name}.svg", f.read_text())
    put(f"{base}/Contents.json", json.dumps({
        "images": [{"filename": f"{name}.svg", "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
        "properties": {"preserves-vector-representation": True},
    }, indent=2) + "\n")

for rel in ("content/words.json", "content/rules.json", "content/curriculum.json"):
    put(f"ios/TamilTrainCore/Sources/TamilTrainCore/Resources/{Path(rel).name}", (SHARED / rel).read_text())


# ------------------------------------------------------------ write / check
def main() -> None:
    check = "--check" in sys.argv
    stale = []
    for path, text in writes.items():
        if path.exists() and path.read_text() == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if check and stale:
        sys.exit("stale generated files (run python3 tools/sync.py):\n  " + "\n  ".join(map(str, stale)))
    print(("checked " if check else "synced ") + f"{len(writes)} files, {len(ART)} art assets")


if __name__ == "__main__":
    main()
